### ISSUE TITLE
Suggestion: Allow more decimals in the account balance

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#11]
The main balance show 0 when there is 0.00002 Nano (can be seen by hitting the ... but I think it can be confusing. What is the rounding limit here anyway? And if Nano increases 100x in value, it may be even more confusing.

**Comment by KodeStar** [comment]
Current rounding is set to 2 decimal places, I think I need to change it though so it only rounds if the balance is over 0.005 or something
