### ISSUE TITLE
Suggestion: Redundant API end points

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#15]
I was imagine some kind of load balancer or failover in case the main API fails. It could be done externally, for example using cloudflare but often involves cost. So what if building it directly into the wallet? A failover API that it will try if the first one fails/timeout? That could be another server with another nano node. Could be very useful when upgrading to a new nano node version for example and still want the wallet uninterrupted during the downtime.

The failover would probably happen after a certain timeout, lets say 2 seconds. However, a problem with this is if the API is down over a longer period all requests will be extended by 2 seconds. Another option would be to call all registered APIs for each call and use the fastest response. That would ensure optimal speed and uptime with the cost that all APIs will have to respond all the time.

**Comment by thelamer** [comment]
Given the URL param would be kinda ugly I think this is best for down streamed wallets , will look into it.

**Comment by thelamer** [comment]
See the method used in the linked commit https://github.com/linuxserver/nano-wallet/commit/29a929c1f97340c56ae741b656fd33fbcd1f5301

This will set to a functional endpoint from an array of them on wallet open. It is not load balancing and the user will need to reload the wallet interface if the downtime occurs while they have their wallet open, but I think this is the best approach to letting downstream wallets avoid having to put a load balancer in front of their RPC endpoints if they choose not to. 

If you ingest this you will need to change your settings to an array ( a single item array is OK)
