### ISSUE TITLE
Suggestion: Better notifications

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#20]
When you copy text data to clipboard there is an alert window. I don't think that's the best approach since you can accidentally disable that on mobile for example and doesn't look very nice plus you have to close it with one extra click every time. A more common method is a custom notification display below the field you copy. For example at tools.nanos.cc I use this library but that's for react. https://github.com/fkhadra/react-toastify

There are tons of solutions for this.

**Comment by KodeStar** [comment]
Resolved by commit https://github.com/linuxserver/nano-wallet/commit/ec571ec27f378a1b41598754d32dc794337b79b2
