### ISSUE TITLE
Suggestion: Support import of nano seed

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#3]
So right now it allows import of private key. I think it would be nice to also allow import of a seed. I don't think it can be detected if a 64 char hex is a seed or a private key. So maybe two fields are required. One for Nano Seed and one for Private key (which would automatically be computed if the seed is entered with account index 0 as default). Also an advanced interface where the user can select any index number.

**Comment by thelamer** [comment]
This is fixed in https://github.com/linuxserver/nano-wallet/releases/tag/1.0.4
