### ISSUE TITLE
Bad behavior in POS logic

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#30]
1. If sending amount larger than given, the notification is not shown (but balance reset as it should). This is true also if doing the payments in steps of smaller amounts.
2. When making a request and paying it in full the polling for pending should stop. That works if paying the full amount in one transaction and also if overpaying in one transaction. But when paying in say two transactions and exactly matching the amount the last payment does not stop the API polling. Which means if you continue to do this in the same session you end up with an infinite amount of pollings per second. Bonus issue is the keypad automatically close on each poll it seems as well when in this state.
3. If the pos account has one or more pending (made to the account since the last session) they will immediately be processed. I think that should be avoided if possible since it will mess with the actual request. That is, only care about pending made after setting the amount.

**Comment by thelamer** [comment]
I have not had time to re loop , but if you are enabling the refresh feature please set POS to false. It will still function but the POS flag is there to not have refreshes run from the wallet view and stop polling. If using refresh polling will never stop in that view.

**Comment by Joohansson** [comment]
Where do I find that POS flag to set to false?

**Comment by thelamer** [comment]
1 and 2 are resolved at head, I am not fully understanding 3. On POS page open we snapshot the pending state and store it to compare to anything new after the receive amount is set. 

That receive amount session is only alive as long as it has a pending balance.

**Comment by Joohansson** [comment]
> 1 and 2 are resolved at head, I am not fully understanding 3. On POS page open we snapshot the pending state and store it to compare to anything new after the receive amount is set.
> 
> That receive amount session is only alive as long as it has a pending balance.

1 and 2 confirmed fixed. 3 depends on when you send. If you send before you load the page, it will not bother with that pending. But if you load the page, send a random amount and then enter the amount, it will react to that pending. I don't think it should and you should take the snapshot when you set an amount, not when you reload the page. But I could be wrong, so I leave that up to you.
