### ISSUE TITLE
Bug: Automatic pending in receive screen does no longer work

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#33]
I have receiverefresh: true (store/app/state.js) but it does no longer refresh the pending while in the receive window (when logged in to the wallet), with or without an amount. It worked before so I'm not sure what broke it. Maybe the latest POS changes (which does work if just using the standalone pos window). Or it's me that screw something up. Needs investigation.

**Comment by thelamer** [comment]
I have re-worked the logic so that there is no more setting for the refresh it is on by default. 
The default wallet view no longer has any logic to replicate the POS stuff to deduct from total owed and stop polling. 
Please test and follow up in https://github.com/linuxserver/nano-wallet/issues/30
