### ISSUE TITLE
Bug: QR reader report invalid amount on decimals

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#37]
The QR scanner is not able to interpret a QR containing an amount with any kind of decimals.

You can test this QR: https://tools.nanos.cc/?tool=pay&address=nano_1gur37mt5cawjg5844bmpg8upo4hbgnbbuwcerdobqoeny4ewoqshowfakfo&amount=0.1&message=Donate%20to%20KeyTools

**Comment by thelamer** [comment]
we were using the wrong conversion when reading , it is why whole numbers worked. fixed at head
