### ISSUE TITLE
Warning before logging out

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#42]
Reddit request: Popup warning when you press logout button. This kind of indicate that you might not have saved your seed so I don't know. I'm fine with either.

**Comment by thelamer** [comment]
We don't even warn on send, I personally really do not like protection popup/popovers they are a pain for power users, my preference when using an app has always been basic form validation. 
What are your thoughts on it? Reddit will request all kinds of shit.

**Comment by Joohansson** [comment]
I think you are right. Too annoying
