### ISSUE TITLE
Suggestion: Simplified url pattern

### ISSUE THREAD

**Issue by Joohansson** [linuxserver/nano-wallet#7]
I like the ability to select backend API for the wallet but I'm not a fan of the long URL pattern. Right now using https://tix.nanos.cc/#/1.nanos.cc which does not look nice.

Suggestion is to add an optional alias to the store/app/state.js

```
'mynano.ninja': {
          alias: 'ninja',
          port: 443,
          path: '/api/node',
          protocol: 'https',
          headers: {
            'Content-Type': 'application/json'
          }
```
Then if the alias is present the URL would switch to example.com/#/ninja

**Comment by thelamer** [comment]
I think this one falls under self documentation, the user should be able to hit the URL they enter, even if that API does not send back any useful information they will understand that is the URL they are pointing it to. 
From a quick launch alias standpoint optimally the downstream api operators would do what you did and just host the wallet themselves with customization.

**Comment by thelamer** [comment]
Gonna leave this open for a bit to ponder, but my initial gut reaction is we should do the full URL in all cases and down-streamers wanting to improve convenience should fork and host.

**Comment by KodeStar** [comment]
This is already basically solved by `changeaddress: false` not needing an address at all

**Comment by thelamer** [comment]
closing I do not think we are going to do this
